spring:
  datasource:
    url: jdbc:mysql://database-adventech.c9w0ek6k6s0s.ap-northeast-2.rds.amazonaws.com:3306/DataHubTest
    username: root
    password: ig26827463
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true